# General
finetune: True
partial_train: null

# Traning
epochs: 150
batch_size: 16
lr: 0.00003
weight_decay: 0.01
lr_decay: 0.99

test_batch_size: 2

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
num_joints: 17
hidden_dim: 2048
dropout_ratio: 0.1

# decoder
dec_num_layers: 12
dec_num_heads: 16

# Data
dataset: walking
data_split: xsub
clip_len: 243

# Augmentation
random_move: True
scale_range_train: [1, 3]
scale_range_test: [2, 2]
